# Generated by Django 3.0.2 on 2020-01-26 09:46

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, default='', max_length=128, verbose_name='Logo IMG')),
                ('logo2x', models.CharField(blank=True, default='', max_length=128, verbose_name='Logo2x IMG')),
                ('text_big', models.CharField(blank=True, default='', max_length=255, verbose_name='Text big')),
                ('text_small', models.CharField(blank=True, default='', max_length=255, verbose_name='Text small')),
                ('position', models.SmallIntegerField(default=10)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=32)),
                ('background', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_top', models.CharField(blank=True, default='', max_length=255)),
                ('text_middle', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(default='', max_length=255), blank=True, size=None)),
                ('text_bottom', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.SmallIntegerField(default=10)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('text', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_big', models.CharField(blank=True, default='', max_length=255, verbose_name='Text big')),
                ('text_small', models.CharField(blank=True, default='', max_length=255, verbose_name='Text small')),
                ('button_title', models.CharField(blank=True, default='', max_length=128)),
                ('button_url', models.CharField(blank=True, default='', max_length=32)),
                ('background', models.CharField(blank=True, default='', max_length=255, verbose_name='Background')),
            ],
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('function', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2x', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('short_name', models.CharField(blank=True, default='', max_length=64)),
                ('social_page', models.CharField(blank=True, default='', max_length=64)),
                ('social_vk', models.CharField(blank=True, default='', max_length=64)),
                ('social_fb', models.CharField(blank=True, default='', max_length=64)),
                ('social_ok', models.CharField(blank=True, default='', max_length=64)),
                ('social_inst', models.CharField(blank=True, default='', max_length=64)),
                ('social_youtube', models.CharField(blank=True, default='', max_length=64)),
                ('position', models.SmallIntegerField(default=10)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.CharField(blank=True, default='', max_length=32)),
                ('position', models.SmallIntegerField(default=10, help_text='<0 is buttons')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video1_url', models.CharField(blank=True, default='', max_length=64)),
                ('video2_url', models.CharField(blank=True, default='', max_length=64)),
                ('position', models.SmallIntegerField(default=10)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='Title')),
                ('keywords', models.CharField(blank=True, default='', max_length=255, verbose_name='keywords')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo2x', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_big', models.CharField(blank=True, default='', max_length=255)),
                ('text_small', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, default='', max_length=128)),
                ('image2x', models.CharField(blank=True, default='', max_length=128)),
                ('services_title', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
