# Generated by Django 3.0.2 on 2020-01-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=32)),
                ('name', models.CharField(default='', max_length=32)),
                ('position', models.SmallIntegerField(default=10)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
