# Generated by Django 3.0.2 on 2020-02-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200201_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minister',
            name='social_fb',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='social_inst',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='social_ok',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='social_page',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='social_vk',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='social_youtube',
        ),
    ]
