# Generated by Django 3.0.2 on 2020-02-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200201_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('desc', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ('email', 'desc'),
                'unique_together': {('email', 'desc')},
            },
        ),
    ]
