# Generated by Django 3.0.2 on 2020-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200201_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendedform',
            name='sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sendedform',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sendedform',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sendedform',
            name='method',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sendedform',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sendedform',
            name='tel',
            field=models.CharField(default='', max_length=64),
        ),
    ]
