# Generated by Django 3.0.2 on 2020-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200201_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='minister',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
